### ISSUE TITLE
Crashes when open

### ISSUE THREAD

**Issue by Asherehsa** [dougkeen/BartRunnerAndroid#2]
Downloaded this app to try and it crashed immediately.

**Comment by jtgans** [comment]
Second this from the F-Droid build. Crash log is as follows from adb:

--------- beginning of crash
E/AndroidRuntime( 5187): FATAL EXCEPTION: main
E/AndroidRuntime( 5187): Process: com.dougkeen.bart, PID: 5187
E/AndroidRuntime( 5187): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.dougkeen.bart/com.dougkeen.bart.activities.RoutesListActivity_}: java.lang.ClassNotFoundException: Didn't find class "com.dougkeen.bart.activities.RoutesListActivity_" on path: DexPathList[[zip file "/data/app/com.dougkeen.bart-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/AndroidRuntime( 5187): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
E/AndroidRuntime( 5187): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2418)
E/AndroidRuntime( 5187): 	at android.app.ActivityThread.access$900(ActivityThread.java:154)
E/AndroidRuntime( 5187): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
E/AndroidRuntime( 5187): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 5187): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 5187): 	at android.app.ActivityThread.main(ActivityThread.java:5289)
E/AndroidRuntime( 5187): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5187): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 5187): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime( 5187): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime( 5187): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.dougkeen.bart.activities.RoutesListActivity_" on path: DexPathList[[zip file "/data/app/com.dougkeen.bart-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/AndroidRuntime( 5187): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 5187): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime( 5187): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime( 5187): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1066)
E/AndroidRuntime( 5187): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257)
E/AndroidRuntime( 5187): 	... 10 more
E/AndroidRuntime( 5187): 	Suppressed: java.lang.ClassNotFoundException: com.dougkeen.bart.activities.RoutesListActivity_
E/AndroidRuntime( 5187): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime( 5187): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime( 5187): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime( 5187): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime( 5187): 		... 13 more
E/AndroidRuntime( 5187): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
W/ActivityManager( 2278):   Force finishing activity 1 com.dougkeen.bart/.activities.RoutesListActivity_

Note: I'm running CyanogenMod 11 on a Nexus 5, so this may be a peculiarity with the art runtime? I'll do some more digging tonight to see if I can fix the issue.

**Comment by dougkeen** [comment]
We'll soon get things updated to use gradle, which should greatly simplify things for the F-Droid build. Stay tuned...

**Comment by dougkeen** [comment]
Ok, latest master revision uses gradle for building. Hopefully this solves the F-droid build issues.

**Comment by jtgans** [comment]
Has the F-Droid build been rebuilt yet? I'm still seeing the exact same stack trace.

**Comment by jtgans** [comment]
Ah, I see now that you are not the one submitting F-Droid builds. I'll go pester the F-Droid folks instead. :-)
